name: Generate QGIS Python Plugins Repository

on:
  push:
    paths:
      - 'plugins/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate plugins.xml
        run: |
          pip install qgis-plugin-repo
          # Wir erstellen die XML. Der Punkt steht für das Zielverzeichnis.
          qgis-plugin-repo merge . plugins/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages